# Stage 1: Install dependencies
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

# Stage 2: Build the app
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG SUPABASE_SERVICE_ROLE_KEY
ARG GEMINI_API_KEY
ARG FATSECRET_CLIENT_ID
ARG FATSECRET_CLIENT_SECRET
ARG SPOONACULAR_API_KEY

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV FATSECRET_CLIENT_ID=$FATSECRET_CLIENT_ID
ENV FATSECRET_CLIENT_SECRET=$FATSECRET_CLIENT_SECRET
ENV SPOONACULAR_API_KEY=$SPOONACULAR_API_KEY

RUN npm run build

# Stage 3: Production image
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# Re-declare ARGs for runtime server-side env vars
ARG SUPABASE_SERVICE_ROLE_KEY
ARG GEMINI_API_KEY
ARG FATSECRET_CLIENT_ID
ARG FATSECRET_CLIENT_SECRET
ARG SPOONACULAR_API_KEY

ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV FATSECRET_CLIENT_ID=$FATSECRET_CLIENT_ID
ENV FATSECRET_CLIENT_SECRET=$FATSECRET_CLIENT_SECRET
ENV SPOONACULAR_API_KEY=$SPOONACULAR_API_KEY

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
